"""SQLAlchemy ORM models for the valuation system."""

import uuid

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    JSON,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql import func

Base = declarative_base()


class CompanyModel(Base):
    """Tracked companies."""

    __tablename__ = "companies"

    id = Column(
        String(36),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    ticker = Column(String(20), unique=True, nullable=False, index=True)
    name = Column(String(100), nullable=False)
    market = Column(String(10), nullable=False)
    industry = Column(String(50), nullable=False)
    competitors = Column(JSON, default=[])
    custom_groups = Column(JSON, default=[])
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, server_default=func.now())


class FinancialStatementsModel(Base):
    """Historical financial statements per ticker and period."""

    __tablename__ = "financial_statements"
    __table_args__ = (
        UniqueConstraint("ticker", "period", name="uq_ticker_period"),
    )

    id = Column(
        String(36),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    ticker = Column(String(20), nullable=False, index=True)
    period = Column(Date, nullable=False)
    market = Column(String(10), nullable=False)
    revenue = Column(Numeric(20, 2))
    net_profit = Column(Numeric(20, 2))
    gross_margin = Column(Float)
    roe = Column(Float)
    contract_liabilities = Column(Numeric(20, 2), nullable=True)
    total_assets = Column(Numeric(20, 2))
    total_liabilities = Column(Numeric(20, 2))
    operating_cashflow = Column(Numeric(20, 2))
    eps = Column(Numeric(10, 4))
    bvps = Column(Numeric(10, 4))
    raw_data = Column(JSON, default={})
    fetched_at = Column(DateTime, server_default=func.now())


class IndustryMetricModel(Base):
    """Industry-specific metrics (TimescaleDB hypertable candidate).

    NOTE: The `industry_metrics` table should be converted to a TimescaleDB
    hypertable partitioned by `recorded_at` via init.sql:
        SELECT create_hypertable('industry_metrics', 'recorded_at');
    """

    __tablename__ = "industry_metrics"
    __table_args__ = (
        Index("ix_industry_metrics_ticker_metric_recorded", "ticker", "metric_name", "recorded_at"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(20), nullable=False, index=True)
    metric_name = Column(String(100), nullable=False)
    metric_value = Column(Float, nullable=False)
    recorded_at = Column(DateTime, nullable=False)
    source = Column(String(50))
    confidence = Column(Float, default=1.0)


class MasterSignalModel(Base):
    """Signals generated by master analysts."""

    __tablename__ = "master_signals"

    id = Column(
        String(36),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    ticker = Column(String(20), nullable=False, index=True)
    master_name = Column(String(30), nullable=False)
    signal = Column(String(10), nullable=False)
    confidence = Column(Float)
    reasoning = Column(Text)
    scoring_details = Column(JSON, default={})
    created_at = Column(DateTime, server_default=func.now())


class DebateRecordModel(Base):
    """Multi-agent debate records."""

    __tablename__ = "debate_records"

    id = Column(
        String(36),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    ticker = Column(String(20), nullable=False, index=True)
    rounds = Column(JSON)
    judge_summary = Column(Text)
    final_stance = Column(String(10))
    confidence = Column(Float)
    key_contentions = Column(JSON, default=[])
    competitor_evidence_used = Column(JSON, default=[])
    created_at = Column(DateTime, server_default=func.now())


class ValuationReportModel(Base):
    """Final valuation reports."""

    __tablename__ = "valuation_reports"

    id = Column(
        String(36),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    ticker = Column(String(20), nullable=False, index=True)
    valuation_low = Column(Numeric(20, 2))
    valuation_mid = Column(Numeric(20, 2))
    valuation_high = Column(Numeric(20, 2))
    pe_quantile = Column(Float)
    bull_arguments = Column(JSON, default=[])
    bear_arguments = Column(JSON, default=[])
    key_assumptions = Column(JSON, default=[])
    sensitivity_factors = Column(JSON, default={})
    competitor_comparison = Column(JSON, default={})
    human_approved = Column(Boolean, default=False)
    approved_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, server_default=func.now())


class ReflectionModel(Base):
    """Post-decision reflections for continuous learning."""

    __tablename__ = "reflections"

    id = Column(
        String(36),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    decision_id = Column(String(36), ForeignKey("valuation_reports.id"), nullable=True)
    ticker = Column(String(20), nullable=False)
    industry = Column(String(50))
    predicted_signal = Column(String(10))
    actual_outcome = Column(Text)
    correct_arguments = Column(JSON, default=[])
    failed_arguments = Column(JSON, default=[])
    lesson_learned = Column(Text)
    embedding = Column(Vector(1024))
    created_at = Column(DateTime, server_default=func.now())


def create_tables(engine) -> None:
    """Create all tables and PostgreSQL extensions used by the system."""
    with engine.begin() as conn:
        if conn.dialect.name == "postgresql":
            conn.execute(text("CREATE EXTENSION IF NOT EXISTS pgcrypto"))
            conn.execute(text("CREATE EXTENSION IF NOT EXISTS timescaledb"))
            conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
    Base.metadata.create_all(engine)
    configure_timescale(engine)


def configure_timescale(engine) -> None:
    """Convert time-series tables to TimescaleDB hypertables when available."""
    with engine.begin() as conn:
        if conn.dialect.name != "postgresql":
            return
        conn.execute(
            text(
                "SELECT create_hypertable("
                "'industry_metrics', 'recorded_at', if_not_exists => TRUE)"
            )
        )
